### ISSUE TITLE
Un paio di errori grammaticali sul sito web

### ISSUE THREAD

**Issue by spartacus04** [BanfiTommasoFelice/Ingegneria_Informatica#1]
Ciao!

Per prima cosa vorrei ringraziare per l'ottimo materiale che hai pubblicato. Lo utilizzerò sicuramente per studiare/ripassare Analisi e Geometria. 

Volevo avvisarti che nella pagina web ci sono un paio di typo. Ho notato principalmente "Info&Discalaimer" nella navbar e nella sezione apposita, e "Apputni" nel footer.

Grazie ancora per gli appunti!

**Comment by BanfiTommasoFelice** [comment]
Ciao, grazie per avermelo fatto notare! Ora ho fixato. 

Mi fa piacere che ti siano utili i miei appunti    :blush::blush:
Considera che non avevo ancora imparato a scrivere bene i documenti con Latex, quelli del secondo semestre sono meglio.

Se posso chiederti un feedback sulle dispense, si riescono a leggere e le pagine scorrono agevolmente o lagga parecchio e ne carica poche alla volta? Perchè per evitare che qualcuno si mettesse a rivedere le dispense stampate, ho optato per caricarle su un sito e "_bloccare_" (lol) la stampa, ma non vorrei che le abbia rese troppo scomode per studiare rispetto ad avere il pdf.

Grazie mille ancora e buona fortuna per gli esami

**Comment by spartacus04** [comment]
Allora le pagine scorrono velocemente e si riescono a leggere, però il sito lagga un bel po quando viene caricata una dispensa. Il caricamento non da fastidio, non è neanche troppo lento, piuchealtro è che l'intera pagina è bloccata e non da segno di vita mentre viene caricata. Se ci fosse un modo di caricare le pagine asincronamente o in modo dinamico sarebbe perfetto (immagino che sia quello che blocca l'event loop). Oltre a questo, almeno sul mio pc, non ci sono problemi di lag o simili.


Grazie mille, in bocca al lupo anche a te per i tuoi esami!

**Comment by BanfiTommasoFelice** [comment]
Grazie mille per il feedback 

close #1
